-- ============================================================================
-- SALES DATA - CORTEX SEMANTIC VIEW + AGENT
-- ============================================================================

USE DATABASE SALES_DATA;
USE SCHEMA PUBLIC;


-- ============================================================================
-- STEP 1: CREATE NATIVE SEMANTIC VIEW
-- ============================================================================
-- IMPORTANT:
-- This is a SEMANTIC VIEW, NOT a dynamic table.
-- The semantic view tells Cortex Analyst:
--   * Which tables exist
--   * How tables join
--   * Which columns are dimensions
--   * Which columns are facts/metrics
-- ============================================================================

CREATE OR REPLACE SEMANTIC VIEW SALES_SEMANTIC_MODEL

TABLES (

    CUSTOMERS AS SALES_DATA.PUBLIC.CUSTOMERS
        PRIMARY KEY (CUSTOMER_ID),

    ORDERS AS SALES_DATA.PUBLIC.ORDERS
        PRIMARY KEY (ORDER_ID),

    ORDER_ITEMS AS SALES_DATA.PUBLIC.ORDER_ITEMS
        PRIMARY KEY (ORDER_ITEM_ID),

    PRODUCTS AS SALES_DATA.PUBLIC.PRODUCTS
        PRIMARY KEY (PRODUCT_ID),

    SALES_REPS AS SALES_DATA.PUBLIC.SALES_REPS
        PRIMARY KEY (REP_ID),

    SALES_PERFORMANCE AS SALES_DATA.PUBLIC.SALES_PERFORMANCE
        PRIMARY KEY (PERF_ID),

    CUSTOMER_SEGMENTS AS SALES_DATA.PUBLIC.CUSTOMER_SEGMENTS
        PRIMARY KEY (SEGMENT_ID),

    PRODUCT_INVENTORY AS SALES_DATA.PUBLIC.PRODUCT_INVENTORY
        PRIMARY KEY (INVENTORY_ID),

    CUSTOMER_LIFETIME_VALUE AS SALES_DATA.PUBLIC.CUSTOMER_LIFETIME_VALUE
        PRIMARY KEY (CLV_ID),

    REP_TERRITORIES AS SALES_DATA.PUBLIC.REP_TERRITORIES
        PRIMARY KEY (TERRITORY_ID)
)

RELATIONSHIPS (

    ORDERS_TO_CUSTOMERS AS
        ORDERS(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),

    ORDERS_TO_REPS AS
        ORDERS(REP_ID) REFERENCES SALES_REPS(REP_ID),

    ORDER_ITEMS_TO_ORDERS AS
        ORDER_ITEMS(ORDER_ID) REFERENCES ORDERS(ORDER_ID),

    ORDER_ITEMS_TO_PRODUCTS AS
        ORDER_ITEMS(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),

    CUSTOMER_SEGMENTS_TO_CUSTOMERS AS
        CUSTOMER_SEGMENTS(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),

    CUSTOMER_LTV_TO_CUSTOMERS AS
        CUSTOMER_LIFETIME_VALUE(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),

    INVENTORY_TO_PRODUCTS AS
        PRODUCT_INVENTORY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),

    REP_TERRITORIES_TO_REPS AS
        REP_TERRITORIES(REP_ID) REFERENCES SALES_REPS(REP_ID)
)

FACTS (

    ORDERS.FINAL_VALUE AS
        ORDERS.FINAL_VALUE,

    ORDER_ITEMS.QUANTITY AS
        ORDER_ITEMS.QUANTITY,

    ORDER_ITEMS.UNIT_PRICE AS
        ORDER_ITEMS.UNIT_PRICE,

    SALES_PERFORMANCE.QUOTA AS
        SALES_PERFORMANCE.QUOTA,

    SALES_PERFORMANCE.ACTUAL_REVENUE AS
        SALES_PERFORMANCE.ACTUAL_REVENUE,

    SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT AS
        SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT,

    SALES_PERFORMANCE.DEALS_WON AS
        SALES_PERFORMANCE.DEALS_WON,

    SALES_PERFORMANCE.DEALS_LOST AS
        SALES_PERFORMANCE.DEALS_LOST,

    SALES_PERFORMANCE.PIPELINE_VALUE AS
        SALES_PERFORMANCE.PIPELINE_VALUE,

    CUSTOMER_LIFETIME_VALUE.TOTAL_REVENUE AS
        CUSTOMER_LIFETIME_VALUE.TOTAL_REVENUE,

    CUSTOMER_LIFETIME_VALUE.PREDICTED_LTV AS
        CUSTOMER_LIFETIME_VALUE.PREDICTED_LTV,

    CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT AS
        CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT,

    CUSTOMER_LIFETIME_VALUE.RENEWAL_LIKELIHOOD_PERCENT AS
        CUSTOMER_LIFETIME_VALUE.RENEWAL_LIKELIHOOD_PERCENT,

    CUSTOMER_LIFETIME_VALUE.AVERAGE_ORDER_VALUE AS
        CUSTOMER_LIFETIME_VALUE.AVERAGE_ORDER_VALUE,

    CUSTOMER_LIFETIME_VALUE.TOTAL_ORDERS AS
        CUSTOMER_LIFETIME_VALUE.TOTAL_ORDERS
)

DIMENSIONS (

    -- CUSTOMERS

    CUSTOMERS.CUSTOMER_ID AS
        CUSTOMERS.CUSTOMER_ID,

    CUSTOMERS.CUSTOMER_NAME AS
        CUSTOMERS.CUSTOMER_NAME,

    CUSTOMERS.INDUSTRY AS
        CUSTOMERS.INDUSTRY,

    CUSTOMERS.COMPANY_SIZE AS
        CUSTOMERS.COMPANY_SIZE,


    -- ORDERS

    ORDERS.ORDER_ID AS
        ORDERS.ORDER_ID,

    ORDERS.CUSTOMER_ID AS
        ORDERS.CUSTOMER_ID,

    ORDERS.REP_ID AS
        ORDERS.REP_ID,

    ORDERS.ORDER_DATE AS
        ORDERS.ORDER_DATE,


    -- ORDER ITEMS

    ORDER_ITEMS.ORDER_ITEM_ID AS
        ORDER_ITEMS.ORDER_ITEM_ID,

    ORDER_ITEMS.ORDER_ID AS
        ORDER_ITEMS.ORDER_ID,

    ORDER_ITEMS.PRODUCT_ID AS
        ORDER_ITEMS.PRODUCT_ID,


    -- PRODUCTS

    PRODUCTS.PRODUCT_ID AS
        PRODUCTS.PRODUCT_ID,

    PRODUCTS.PRODUCT_NAME AS
        PRODUCTS.PRODUCT_NAME,

    PRODUCTS.CATEGORY AS
        PRODUCTS.CATEGORY,

    PRODUCTS.PRICE AS
        PRODUCTS.PRICE,


    -- SALES REPS

    SALES_REPS.REP_ID AS
        SALES_REPS.REP_ID,

    SALES_REPS.REP_NAME AS
        SALES_REPS.REP_NAME,

    SALES_REPS.TERRITORY AS
        SALES_REPS.TERRITORY,

    SALES_REPS.MANAGER AS
        SALES_REPS.MANAGER,


    -- SALES PERFORMANCE

    SALES_PERFORMANCE.PERF_ID AS
        SALES_PERFORMANCE.PERF_ID,

    SALES_PERFORMANCE.REP_ID AS
        SALES_PERFORMANCE.REP_ID,

    SALES_PERFORMANCE.PERFORMANCE_MONTH AS
        SALES_PERFORMANCE.PERFORMANCE_MONTH,


    -- CUSTOMER SEGMENTS

    CUSTOMER_SEGMENTS.SEGMENT_ID AS
        CUSTOMER_SEGMENTS.SEGMENT_ID,

    CUSTOMER_SEGMENTS.CUSTOMER_ID AS
        CUSTOMER_SEGMENTS.CUSTOMER_ID,

    CUSTOMER_SEGMENTS.SEGMENT_NAME AS
        CUSTOMER_SEGMENTS.SEGMENT_NAME,

    CUSTOMER_SEGMENTS.BEHAVIOR_SCORE AS
        CUSTOMER_SEGMENTS.BEHAVIOR_SCORE,


    -- INVENTORY

    PRODUCT_INVENTORY.INVENTORY_ID AS
        PRODUCT_INVENTORY.INVENTORY_ID,

    PRODUCT_INVENTORY.PRODUCT_ID AS
        PRODUCT_INVENTORY.PRODUCT_ID,

    PRODUCT_INVENTORY.QUANTITY_AVAILABLE AS
        PRODUCT_INVENTORY.QUANTITY_AVAILABLE,

    PRODUCT_INVENTORY.REORDER_LEVEL AS
        PRODUCT_INVENTORY.REORDER_LEVEL,

    PRODUCT_INVENTORY.LAST_RESTOCKED_DATE AS
        PRODUCT_INVENTORY.LAST_RESTOCKED_DATE,


    -- CUSTOMER LIFETIME VALUE

    CUSTOMER_LIFETIME_VALUE.CLV_ID AS
        CUSTOMER_LIFETIME_VALUE.CLV_ID,

    CUSTOMER_LIFETIME_VALUE.CUSTOMER_ID AS
        CUSTOMER_LIFETIME_VALUE.CUSTOMER_ID,

    CUSTOMER_LIFETIME_VALUE.LAST_ORDER_DATE AS
        CUSTOMER_LIFETIME_VALUE.LAST_ORDER_DATE,


    -- TERRITORIES

    REP_TERRITORIES.TERRITORY_ID AS
        REP_TERRITORIES.TERRITORY_ID,

    REP_TERRITORIES.REP_ID AS
        REP_TERRITORIES.REP_ID,

    REP_TERRITORIES.REGION AS
        REP_TERRITORIES.REGION
)

METRICS (

    ORDERS.TOTAL_REVENUE AS
        SUM(ORDERS.FINAL_VALUE),

    ORDERS.ORDER_COUNT AS
        COUNT(DISTINCT ORDERS.ORDER_ID),

    ORDER_ITEMS.TOTAL_QUANTITY AS
        SUM(ORDER_ITEMS.QUANTITY),

    ORDER_ITEMS.AVERAGE_UNIT_PRICE AS
        AVG(ORDER_ITEMS.UNIT_PRICE),

    SALES_PERFORMANCE.TOTAL_QUOTA AS
        SUM(SALES_PERFORMANCE.QUOTA),

    SALES_PERFORMANCE.TOTAL_ACTUAL_REVENUE AS
        SUM(SALES_PERFORMANCE.ACTUAL_REVENUE),

    SALES_PERFORMANCE.AVERAGE_QUOTA_ATTAINMENT AS
        AVG(SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT),

    SALES_PERFORMANCE.TOTAL_DEALS_WON AS
        SUM(SALES_PERFORMANCE.DEALS_WON),

    SALES_PERFORMANCE.TOTAL_DEALS_LOST AS
        SUM(SALES_PERFORMANCE.DEALS_LOST),

    SALES_PERFORMANCE.TOTAL_PIPELINE_VALUE AS
        SUM(SALES_PERFORMANCE.PIPELINE_VALUE),

    CUSTOMER_LIFETIME_VALUE.TOTAL_CUSTOMER_REVENUE AS
        SUM(CUSTOMER_LIFETIME_VALUE.TOTAL_REVENUE),

    CUSTOMER_LIFETIME_VALUE.AVERAGE_PREDICTED_LTV AS
        AVG(CUSTOMER_LIFETIME_VALUE.PREDICTED_LTV),

    CUSTOMER_LIFETIME_VALUE.AVERAGE_CHURN_RISK AS
        AVG(CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT),

    CUSTOMER_LIFETIME_VALUE.AVERAGE_RENEWAL_LIKELIHOOD AS
        AVG(CUSTOMER_LIFETIME_VALUE.RENEWAL_LIKELIHOOD_PERCENT),

    CUSTOMER_LIFETIME_VALUE.AVERAGE_ORDER_VALUE AS
        AVG(CUSTOMER_LIFETIME_VALUE.AVERAGE_ORDER_VALUE),

    CUSTOMER_LIFETIME_VALUE.TOTAL_CUSTOMER_ORDERS AS
        SUM(CUSTOMER_LIFETIME_VALUE.TOTAL_ORDERS)
);


-- ============================================================================
-- STEP 2: VERIFY SEMANTIC VIEW
-- ============================================================================

SHOW SEMANTIC VIEWS
IN SCHEMA SALES_DATA.PUBLIC;

DESCRIBE SEMANTIC VIEW
SALES_DATA.PUBLIC.SALES_SEMANTIC_MODEL;


-- ============================================================================
-- STEP 3: CREATE CORTEX AGENT
-- ============================================================================

CREATE OR REPLACE AGENT SALES_DATA.PUBLIC.SNOWFLAKE_DATA_AGENT

COMMENT = 'Cortex Agent for Sales Data Analysis'

FROM SPECIFICATION
$$

models:
  orchestration: auto

instructions:

  response: |
    You are an expert sales data analyst helping business users
    understand and analyze their sales data.

    Use the Sales_Analyst tool whenever the user asks a question
    requiring sales data.

    Always provide a clear business-oriented explanation of the result.

    Business Rules:

    CHURN RISK:
      HIGH = greater than 25%
      MEDIUM = 15% to 25%
      LOW = less than 15%

    QUOTA ATTAINMENT:
      EXCEEDING = greater than 110%
      ON_TRACK = 85% to 110%
      UNDERPERFORMING = less than 85%

    PRODUCT GROWTH:
      HIGH = greater than 15%
      MODERATE = 5% to 15%
      DECLINING = less than 5%

    INVENTORY STATUS:
      CRITICAL = quantity available less than reorder level
      WARNING = quantity available less than 1.5 times reorder level
      OK = quantity available greater than or equal to 1.5 times reorder level

    Response Guidelines:

    1. Answer the user's question directly.
    2. Use the Sales_Analyst tool for data-related questions.
    3. Do not invent data.
    4. Clearly explain calculations and business classifications.
    5. Highlight important risks or exceptions.
    6. Provide concise business insights.
    7. When appropriate, provide recommended actions.

  orchestration: |
    Use the Sales_Analyst tool for questions involving:
    - Customers
    - Orders
    - Products
    - Sales representatives
    - Sales performance
    - Customer lifetime value
    - Churn risk
    - Quota attainment
    - Inventory
    - Territories
    - Revenue analysis

tools:

  - tool_spec:
      type: cortex_analyst_text_to_sql
      name: Sales_Analyst
      description: >
        Analyzes sales data using the SALES_SEMANTIC_MODEL semantic view.
        Use this tool to answer questions about customers, orders,
        products, sales representatives, sales performance,
        customer lifetime value, inventory and territories.

tool_resources:

  Sales_Analyst:
    semantic_view: SALES_DATA.PUBLIC.SALES_SEMANTIC_MODEL

$$;


-- ============================================================================
-- STEP 4: GRANT REQUIRED ACCESS
-- ============================================================================

GRANT USAGE
ON DATABASE SALES_DATA
TO ROLE ACCOUNTADMIN;

GRANT USAGE
ON SCHEMA SALES_DATA.PUBLIC
TO ROLE ACCOUNTADMIN;

GRANT SELECT
ON ALL TABLES
IN SCHEMA SALES_DATA.PUBLIC
TO ROLE ACCOUNTADMIN;

GRANT USAGE
ON AGENT SALES_DATA.PUBLIC.SNOWFLAKE_DATA_AGENT
TO ROLE ACCOUNTADMIN;


-- ============================================================================
-- STEP 5: VERIFY AGENT
-- ============================================================================

SHOW AGENTS
IN SCHEMA SALES_DATA.PUBLIC;

DESCRIBE AGENT
SALES_DATA.PUBLIC.SNOWFLAKE_DATA_AGENT;