USE DATABASE SALES_DATA;
USE SCHEMA PUBLIC;

CREATE OR REPLACE SEMANTIC VIEW SALES_SEMANTIC_MODEL

TABLES (
    CUSTOMERS AS SALES_DATA.PUBLIC.CUSTOMERS
        PRIMARY KEY (CUSTOMER_ID),

    PRODUCTS AS SALES_DATA.PUBLIC.PRODUCTS
        PRIMARY KEY (PRODUCT_ID),

    SALES_REPS AS SALES_DATA.PUBLIC.SALES_REPS
        PRIMARY KEY (REP_ID),

    ORDERS AS SALES_DATA.PUBLIC.ORDERS
        PRIMARY KEY (ORDER_ID),

    ORDER_ITEMS AS SALES_DATA.PUBLIC.ORDER_ITEMS
        PRIMARY KEY (LINE_ITEM_ID),

    CUSTOMER_SEGMENTS AS SALES_DATA.PUBLIC.CUSTOMER_SEGMENTS
        PRIMARY KEY (CUSTOMER_ID),

    PRODUCT_INVENTORY AS SALES_DATA.PUBLIC.PRODUCT_INVENTORY
        PRIMARY KEY (INVENTORY_ID),

    CUSTOMER_LIFETIME_VALUE AS SALES_DATA.PUBLIC.CUSTOMER_LIFETIME_VALUE
        PRIMARY KEY (CUSTOMER_ID),

    SALES_PERFORMANCE AS SALES_DATA.PUBLIC.SALES_PERFORMANCE
        PRIMARY KEY (PERFORMANCE_ID),

    REP_TERRITORIES AS SALES_DATA.PUBLIC.REP_TERRITORIES
        PRIMARY KEY (TERRITORY_ID),

    PRODUCT_DEMAND_FREQUENCY AS SALES_DATA.PUBLIC.PRODUCT_DEMAND_FREQUENCY
        PRIMARY KEY (FREQUENCY_ID),

    MONTHLY_SALES_TRENDS AS SALES_DATA.PUBLIC.MONTHLY_SALES_TRENDS
        PRIMARY KEY (TREND_ID),

    DEMAND_FORECAST AS SALES_DATA.PUBLIC.DEMAND_FORECAST
        PRIMARY KEY (FORECAST_ID)
)

RELATIONSHIPS (

    ORDERS_TO_CUSTOMERS AS
        ORDERS(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),

    ORDERS_TO_REPS AS
        ORDERS(REP_ID) REFERENCES SALES_REPS(REP_ID),

    ORDER_ITEMS_TO_ORDERS AS
        ORDER_ITEMS(ORDER_ID) REFERENCES ORDERS(ORDER_ID),

    ORDER_ITEMS_TO_PRODUCTS AS
        ORDER_ITEMS(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),

    SEGMENTS_TO_CUSTOMERS AS
        CUSTOMER_SEGMENTS(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),

    LTV_TO_CUSTOMERS AS
        CUSTOMER_LIFETIME_VALUE(CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    INVENTORY_TO_PRODUCTS AS
        PRODUCT_INVENTORY(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID),

    PERFORMANCE_TO_REPS AS
        SALES_PERFORMANCE(REP_ID)
        REFERENCES SALES_REPS(REP_ID),

    TERRITORIES_TO_REPS AS
        REP_TERRITORIES(REP_ID)
        REFERENCES SALES_REPS(REP_ID),

    DEMAND_FREQUENCY_TO_PRODUCTS AS
        PRODUCT_DEMAND_FREQUENCY(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID),

    SALES_TRENDS_TO_PRODUCTS AS
        MONTHLY_SALES_TRENDS(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID),

    FORECAST_TO_PRODUCTS AS
        DEMAND_FORECAST(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
)
FACTS (

    ORDERS.DEAL_VALUE AS ORDERS.DEAL_VALUE,
    ORDERS.FINAL_VALUE AS ORDERS.FINAL_VALUE,

    ORDER_ITEMS.QUANTITY AS ORDER_ITEMS.QUANTITY,
    ORDER_ITEMS.UNIT_PRICE AS ORDER_ITEMS.UNIT_PRICE,
    ORDER_ITEMS.LINE_TOTAL AS ORDER_ITEMS.LINE_TOTAL,

    PRODUCTS.UNIT_PRICE AS PRODUCTS.UNIT_PRICE,
    PRODUCTS.LIST_PRICE AS PRODUCTS.LIST_PRICE,
    PRODUCTS.COST_PRICE AS PRODUCTS.COST_PRICE,

    SALES_REPS.QUOTA AS SALES_REPS.QUOTA,
    SALES_REPS.BASE_SALARY AS SALES_REPS.BASE_SALARY,
    SALES_REPS.COMMISSION_PERCENT AS SALES_REPS.COMMISSION_PERCENT,

    CUSTOMER_SEGMENTS.SEGMENT_SCORE AS CUSTOMER_SEGMENTS.SEGMENT_SCORE,
    CUSTOMER_SEGMENTS.RISK_SCORE AS CUSTOMER_SEGMENTS.RISK_SCORE,
    CUSTOMER_SEGMENTS.AVERAGE_DEAL_SIZE AS CUSTOMER_SEGMENTS.AVERAGE_DEAL_SIZE,

    PRODUCT_INVENTORY.QUANTITY_ON_HAND AS PRODUCT_INVENTORY.QUANTITY_ON_HAND,
    PRODUCT_INVENTORY.QUANTITY_RESERVED AS PRODUCT_INVENTORY.QUANTITY_RESERVED,
    PRODUCT_INVENTORY.QUANTITY_AVAILABLE AS PRODUCT_INVENTORY.QUANTITY_AVAILABLE,
    PRODUCT_INVENTORY.REORDER_LEVEL AS PRODUCT_INVENTORY.REORDER_LEVEL,

    CUSTOMER_LIFETIME_VALUE.TOTAL_REVENUE AS CUSTOMER_LIFETIME_VALUE.TOTAL_REVENUE,
    CUSTOMER_LIFETIME_VALUE.TOTAL_ORDERS AS CUSTOMER_LIFETIME_VALUE.TOTAL_ORDERS,
    CUSTOMER_LIFETIME_VALUE.PREDICTED_LTV AS CUSTOMER_LIFETIME_VALUE.PREDICTED_LTV,
    CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT AS CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT,
    CUSTOMER_LIFETIME_VALUE.RENEWAL_LIKELIHOOD_PERCENT AS CUSTOMER_LIFETIME_VALUE.RENEWAL_LIKELIHOOD_PERCENT,
    CUSTOMER_LIFETIME_VALUE.AVERAGE_ORDER_VALUE AS CUSTOMER_LIFETIME_VALUE.AVERAGE_ORDER_VALUE,

    SALES_PERFORMANCE.QUOTA AS SALES_PERFORMANCE.QUOTA,
    SALES_PERFORMANCE.ACTUAL_REVENUE AS SALES_PERFORMANCE.ACTUAL_REVENUE,
    SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT AS SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT,
    SALES_PERFORMANCE.DEALS_WON AS SALES_PERFORMANCE.DEALS_WON,
    SALES_PERFORMANCE.DEALS_LOST AS SALES_PERFORMANCE.DEALS_LOST,
    SALES_PERFORMANCE.PIPELINE_VALUE AS SALES_PERFORMANCE.PIPELINE_VALUE,

    PRODUCT_DEMAND_FREQUENCY.TOTAL_UNITS_SOLD AS PRODUCT_DEMAND_FREQUENCY.TOTAL_UNITS_SOLD,
    PRODUCT_DEMAND_FREQUENCY.TOTAL_REVENUE AS PRODUCT_DEMAND_FREQUENCY.TOTAL_REVENUE,
    PRODUCT_DEMAND_FREQUENCY.GROWTH_TREND_PERCENT AS PRODUCT_DEMAND_FREQUENCY.GROWTH_TREND_PERCENT,

    MONTHLY_SALES_TRENDS.UNITS_SOLD AS MONTHLY_SALES_TRENDS.UNITS_SOLD,
    MONTHLY_SALES_TRENDS.REVENUE AS MONTHLY_SALES_TRENDS.REVENUE,
    MONTHLY_SALES_TRENDS.MONTH_OVER_MONTH_GROWTH_PERCENT AS MONTHLY_SALES_TRENDS.MONTH_OVER_MONTH_GROWTH_PERCENT,
    MONTHLY_SALES_TRENDS.YEAR_OVER_YEAR_GROWTH_PERCENT AS MONTHLY_SALES_TRENDS.YEAR_OVER_YEAR_GROWTH_PERCENT,

    DEMAND_FORECAST.FORECASTED_UNITS AS DEMAND_FORECAST.FORECASTED_UNITS,
    DEMAND_FORECAST.FORECASTED_REVENUE AS DEMAND_FORECAST.FORECASTED_REVENUE,
    DEMAND_FORECAST.CONFIDENCE_LEVEL_PERCENT AS DEMAND_FORECAST.CONFIDENCE_LEVEL_PERCENT,
    DEMAND_FORECAST.RECOMMENDED_INVENTORY_LEVEL AS DEMAND_FORECAST.RECOMMENDED_INVENTORY_LEVEL
)
DIMENSIONS (

    CUSTOMERS.CUSTOMER_ID AS CUSTOMERS.CUSTOMER_ID,
    CUSTOMERS.CUSTOMER_NAME AS CUSTOMERS.CUSTOMER_NAME,
    CUSTOMERS.INDUSTRY AS CUSTOMERS.INDUSTRY,
    CUSTOMERS.COMPANY_SIZE AS CUSTOMERS.COMPANY_SIZE,
    CUSTOMERS.COUNTRY AS CUSTOMERS.COUNTRY,
    CUSTOMERS.STATE AS CUSTOMERS.STATE,
    CUSTOMERS.CITY AS CUSTOMERS.CITY,
    CUSTOMERS.SUBSCRIPTION_TIER AS CUSTOMERS.SUBSCRIPTION_TIER,

    PRODUCTS.PRODUCT_ID AS PRODUCTS.PRODUCT_ID,
    PRODUCTS.PRODUCT_NAME AS PRODUCTS.PRODUCT_NAME,
    PRODUCTS.PRODUCT_CATEGORY AS PRODUCTS.PRODUCT_CATEGORY,
    PRODUCTS.PRODUCT_LINE AS PRODUCTS.PRODUCT_LINE,
    PRODUCTS.STATUS AS PRODUCTS.STATUS,

    SALES_REPS.REP_ID AS SALES_REPS.REP_ID,
    SALES_REPS.REP_NAME AS SALES_REPS.REP_NAME,
    SALES_REPS.REGION AS SALES_REPS.REGION,
    SALES_REPS.COMPENSATION_TYPE AS SALES_REPS.COMPENSATION_TYPE,

    ORDERS.ORDER_ID AS ORDERS.ORDER_ID,
    ORDERS.CUSTOMER_ID AS ORDERS.CUSTOMER_ID,
    ORDERS.REP_ID AS ORDERS.REP_ID,
    ORDERS.ORDER_DATE AS ORDERS.ORDER_DATE,
    ORDERS.ORDER_MONTH AS ORDERS.ORDER_MONTH,
    ORDERS.ORDER_STATUS AS ORDERS.ORDER_STATUS,
    ORDERS.CHANNEL AS ORDERS.CHANNEL,
    ORDERS.DEAL_TYPE AS ORDERS.DEAL_TYPE,

    ORDER_ITEMS.LINE_ITEM_ID AS ORDER_ITEMS.LINE_ITEM_ID,
    ORDER_ITEMS.ORDER_ID AS ORDER_ITEMS.ORDER_ID,
    ORDER_ITEMS.PRODUCT_ID AS ORDER_ITEMS.PRODUCT_ID,

    CUSTOMER_SEGMENTS.SEGMENT_NAME AS CUSTOMER_SEGMENTS.SEGMENT_NAME,
    CUSTOMER_SEGMENTS.PURCHASE_FREQUENCY AS CUSTOMER_SEGMENTS.PURCHASE_FREQUENCY,
    CUSTOMER_SEGMENTS.ENGAGEMENT_LEVEL AS CUSTOMER_SEGMENTS.ENGAGEMENT_LEVEL,

    PRODUCT_INVENTORY.WAREHOUSE_LOCATION AS PRODUCT_INVENTORY.WAREHOUSE_LOCATION,
    PRODUCT_INVENTORY.LAST_RESTOCK_DATE AS PRODUCT_INVENTORY.LAST_RESTOCK_DATE,
    PRODUCT_INVENTORY.NEXT_RESTOCK_DATE AS PRODUCT_INVENTORY.NEXT_RESTOCK_DATE,

    CUSTOMER_LIFETIME_VALUE.FIRST_ORDER_DATE AS CUSTOMER_LIFETIME_VALUE.FIRST_ORDER_DATE,
    CUSTOMER_LIFETIME_VALUE.LAST_ORDER_DATE AS CUSTOMER_LIFETIME_VALUE.LAST_ORDER_DATE,

    SALES_PERFORMANCE.PERFORMANCE_MONTH AS SALES_PERFORMANCE.PERFORMANCE_MONTH,

    REP_TERRITORIES.TERRITORY_NAME AS REP_TERRITORIES.TERRITORY_NAME,
    REP_TERRITORIES.COUNTRY AS REP_TERRITORIES.COUNTRY,
    REP_TERRITORIES.STATE AS REP_TERRITORIES.STATE,
    REP_TERRITORIES.REGION AS REP_TERRITORIES.REGION,

    PRODUCT_DEMAND_FREQUENCY.PRODUCT_NAME AS PRODUCT_DEMAND_FREQUENCY.PRODUCT_NAME,
    PRODUCT_DEMAND_FREQUENCY.PURCHASE_FREQUENCY AS PRODUCT_DEMAND_FREQUENCY.PURCHASE_FREQUENCY,
    PRODUCT_DEMAND_FREQUENCY.PEAK_SEASON AS PRODUCT_DEMAND_FREQUENCY.PEAK_SEASON,

    MONTHLY_SALES_TRENDS.PRODUCT_NAME AS MONTHLY_SALES_TRENDS.PRODUCT_NAME,
    MONTHLY_SALES_TRENDS.SALES_MONTH AS MONTHLY_SALES_TRENDS.SALES_MONTH,

    DEMAND_FORECAST.PRODUCT_NAME AS DEMAND_FORECAST.PRODUCT_NAME,
    DEMAND_FORECAST.FORECAST_MONTH AS DEMAND_FORECAST.FORECAST_MONTH,
    DEMAND_FORECAST.RISK_LEVEL AS DEMAND_FORECAST.RISK_LEVEL
)

;

CREATE OR REPLACE AGENT SALES_DATA.PUBLIC.SNOWFLAKE_DATA_AGENT
COMMENT = 'Cortex Agent for Sales Data Analysis'
FROM SPECIFICATION
$$

models:
  orchestration: auto

instructions:

  response: |
    You are an expert sales data analyst.

    Use the Sales_Analyst tool to answer questions
    about sales data.

    Business rules:

    CHURN RISK:
    - HIGH: greater than 25%
    - MEDIUM: 15% to 25%
    - LOW: less than 15%

    QUOTA ATTAINMENT:
    - EXCEEDING: greater than 110%
    - ON_TRACK: 85% to 110%
    - UNDERPERFORMING: less than 85%

    PRODUCT GROWTH:
    - HIGH: greater than 15%
    - MODERATE: 5% to 15%
    - DECLINING: less than 5%

    INVENTORY:
    - CRITICAL: quantity available < reorder level
    - WARNING: quantity available < 1.5 * reorder level
    - OK: quantity available >= 1.5 * reorder level

    Always explain the result in business-friendly language.
    Do not invent data.
    Highlight important risks and exceptions.

  orchestration: |
    Use Sales_Analyst for questions involving customers,
    orders, products, sales representatives, sales performance,
    customer lifetime value, inventory, product demand,
    sales trends, and forecasts.

tools:

  - tool_spec:
      type: cortex_analyst_text_to_sql
      name: Sales_Analyst
      description: >
        Analyzes sales data using the SALES_SEMANTIC_MODEL
        semantic view.

tool_resources:

  Sales_Analyst:
    semantic_view: SALES_DATA.PUBLIC.SALES_SEMANTIC_MODEL

$$;

