-- ============================================================================
-- AUTOMATIC AUDIT LOGGING FOR ANALYST UI QUERIES
-- ============================================================================
-- Purpose: Automatically capture all Analyst questions asked in Snowflake UI
-- How: Background task scans query history every minute
--      Finds all Analyst queries
--      Auto-inserts them into ANALYST_QUERY_LOG
-- Database: SALES_DATA
-- Schema: PUBLIC
-- ============================================================================

USE DATABASE SALES_DATA;
USE SCHEMA PUBLIC;


-- ============================================================================
--  SNOWFLAKE SEMANTIC VIEW FOR ANALYST 
-- ============================================================================
-- Purpose: Create semantic view for Snowflake Analyst 
-- Database: SALES_DATA
-- Schema: PUBLIC
-- Semantic View: SALES_SEMANTIC_MODEL
-- Log Table: ANALYST_QUERY_LOG
-- ============================================================================

-- ============================================================================
-- CREATE SEMANTIC VIEW (for Analyst only)
-- ============================================================================

-- ============================================================================
-- SALES DATA CORTEX ANALYST SEMANTIC VIEW
-- ============================================================================
-- Database : SALES_DATA
-- Schema   : PUBLIC
-- Object   : SALES_SEMANTIC_MODEL
--
-- Purpose:
--   Native Snowflake Semantic View for Cortex Analyst / Cortex Agent.
--
-- Includes:
--   1. Business entities
--   2. Relationships
--   3. Row-level facts
--   4. Business dimensions
--   5. Business metrics
--
-- Source tables:
--   CUSTOMERS
--   PRODUCTS
--   SALES_REPS
--   REP_TERRITORIES
--   ORDERS
--   ORDER_ITEMS
--   CUSTOMER_SEGMENTS
--   PRODUCT_INVENTORY
--   CUSTOMER_LIFETIME_VALUE
--   SALES_PERFORMANCE
--   PRODUCT_DEMAND_FREQUENCY
--   MONTHLY_SALES_TRENDS
--   DEMAND_FORECAST
--
-- Excluded:
--   AGENT_QUERY_AUDIT
--   AGENT_PERFORMANCE_METRICS
--   AGENT_ACTION_LOG
--
-- These are operational/audit tables and should not be part of the
-- business semantic model.
-- ============================================================================

-- ============================================================================
-- CREATE SEMANTIC VIEW
-- ============================================================================

CREATE OR REPLACE SEMANTIC VIEW SALES_SEMANTIC_MODEL


-- ============================================================================
-- 1. LOGICAL TABLES
-- ============================================================================

TABLES (

    CUSTOMERS AS SALES_DATA.PUBLIC.CUSTOMERS
        PRIMARY KEY (CUSTOMER_ID),

    PRODUCTS AS SALES_DATA.PUBLIC.PRODUCTS
        PRIMARY KEY (PRODUCT_ID),

    SALES_REPS AS SALES_DATA.PUBLIC.SALES_REPS
        PRIMARY KEY (REP_ID),

    REP_TERRITORIES AS SALES_DATA.PUBLIC.REP_TERRITORIES
        PRIMARY KEY (TERRITORY_ID),

    ORDERS AS SALES_DATA.PUBLIC.ORDERS
        PRIMARY KEY (ORDER_ID),

    ORDER_ITEMS AS SALES_DATA.PUBLIC.ORDER_ITEMS
        PRIMARY KEY (LINE_ITEM_ID),

    CUSTOMER_SEGMENTS AS SALES_DATA.PUBLIC.CUSTOMER_SEGMENTS
        PRIMARY KEY (CUSTOMER_ID),

    PRODUCT_INVENTORY AS SALES_DATA.PUBLIC.PRODUCT_INVENTORY
        PRIMARY KEY (INVENTORY_ID),

    CUSTOMER_LIFETIME_VALUE AS SALES_DATA.PUBLIC.CUSTOMER_LIFETIME_VALUE
        PRIMARY KEY (CUSTOMER_ID),

    SALES_PERFORMANCE AS SALES_DATA.PUBLIC.SALES_PERFORMANCE
        PRIMARY KEY (PERFORMANCE_ID),

    PRODUCT_DEMAND_FREQUENCY AS SALES_DATA.PUBLIC.PRODUCT_DEMAND_FREQUENCY
        PRIMARY KEY (FREQUENCY_ID),

    MONTHLY_SALES_TRENDS AS SALES_DATA.PUBLIC.MONTHLY_SALES_TRENDS
        PRIMARY KEY (TREND_ID),

    DEMAND_FORECAST AS SALES_DATA.PUBLIC.DEMAND_FORECAST
        PRIMARY KEY (FORECAST_ID)
)


-- ============================================================================
-- 2. RELATIONSHIPS
-- ============================================================================

RELATIONSHIPS (

    ORDERS_TO_CUSTOMERS AS
        ORDERS(CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    ORDERS_TO_REPS AS
        ORDERS(REP_ID)
        REFERENCES SALES_REPS(REP_ID),

    ORDER_ITEMS_TO_ORDERS AS
        ORDER_ITEMS(ORDER_ID)
        REFERENCES ORDERS(ORDER_ID),

    ORDER_ITEMS_TO_PRODUCTS AS
        ORDER_ITEMS(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID),

    SEGMENTS_TO_CUSTOMERS AS
        CUSTOMER_SEGMENTS(CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    LTV_TO_CUSTOMERS AS
        CUSTOMER_LIFETIME_VALUE(CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    INVENTORY_TO_PRODUCTS AS
        PRODUCT_INVENTORY(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID),

    PERFORMANCE_TO_REPS AS
        SALES_PERFORMANCE(REP_ID)
        REFERENCES SALES_REPS(REP_ID),

    TERRITORIES_TO_REPS AS
        REP_TERRITORIES(REP_ID)
        REFERENCES SALES_REPS(REP_ID),

    DEMAND_FREQUENCY_TO_PRODUCTS AS
        PRODUCT_DEMAND_FREQUENCY(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID),

    SALES_TRENDS_TO_PRODUCTS AS
        MONTHLY_SALES_TRENDS(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID),

    FORECAST_TO_PRODUCTS AS
        DEMAND_FORECAST(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
)


-- ============================================================================
-- 3. FACTS
-- ============================================================================
-- Facts are row-level values.
-- Metrics below aggregate these values.
-- ============================================================================

FACTS (

    -- ORDERS
    ORDERS.DEAL_VALUE AS ORDERS.DEAL_VALUE,
    ORDERS.FINAL_VALUE AS ORDERS.FINAL_VALUE,
    ORDERS.DISCOUNT_PERCENT AS ORDERS.DISCOUNT_PERCENT,

    -- ORDER ITEMS
    ORDER_ITEMS.QUANTITY AS ORDER_ITEMS.QUANTITY,
    ORDER_ITEMS.UNIT_PRICE AS ORDER_ITEMS.UNIT_PRICE,
    ORDER_ITEMS.LINE_TOTAL AS ORDER_ITEMS.LINE_TOTAL,
    ORDER_ITEMS.DISCOUNT_APPLIED AS ORDER_ITEMS.DISCOUNT_APPLIED,

    -- PRODUCTS
    PRODUCTS.UNIT_PRICE AS PRODUCTS.UNIT_PRICE,
    PRODUCTS.LIST_PRICE AS PRODUCTS.LIST_PRICE,
    PRODUCTS.COST_PRICE AS PRODUCTS.COST_PRICE,

    -- SALES REPS
    SALES_REPS.QUOTA AS SALES_REPS.QUOTA,
    SALES_REPS.BASE_SALARY AS SALES_REPS.BASE_SALARY,
    SALES_REPS.COMMISSION_PERCENT AS SALES_REPS.COMMISSION_PERCENT,

    -- CUSTOMER SEGMENTS
    CUSTOMER_SEGMENTS.SEGMENT_SCORE AS CUSTOMER_SEGMENTS.SEGMENT_SCORE,
    CUSTOMER_SEGMENTS.AVERAGE_DEAL_SIZE AS CUSTOMER_SEGMENTS.AVERAGE_DEAL_SIZE,
    CUSTOMER_SEGMENTS.PAYMENT_TERMS AS CUSTOMER_SEGMENTS.PAYMENT_TERMS,
    CUSTOMER_SEGMENTS.RISK_SCORE AS CUSTOMER_SEGMENTS.RISK_SCORE,

    -- INVENTORY
    PRODUCT_INVENTORY.QUANTITY_ON_HAND AS PRODUCT_INVENTORY.QUANTITY_ON_HAND,
    PRODUCT_INVENTORY.QUANTITY_RESERVED AS PRODUCT_INVENTORY.QUANTITY_RESERVED,
    PRODUCT_INVENTORY.QUANTITY_AVAILABLE AS PRODUCT_INVENTORY.QUANTITY_AVAILABLE,
    PRODUCT_INVENTORY.REORDER_LEVEL AS PRODUCT_INVENTORY.REORDER_LEVEL,

    -- CUSTOMER LIFETIME VALUE
    CUSTOMER_LIFETIME_VALUE.TOTAL_REVENUE
        AS CUSTOMER_LIFETIME_VALUE.TOTAL_REVENUE,

    CUSTOMER_LIFETIME_VALUE.TOTAL_ORDERS
        AS CUSTOMER_LIFETIME_VALUE.TOTAL_ORDERS,

    CUSTOMER_LIFETIME_VALUE.DAYS_AS_CUSTOMER
        AS CUSTOMER_LIFETIME_VALUE.DAYS_AS_CUSTOMER,

    CUSTOMER_LIFETIME_VALUE.AVERAGE_ORDER_VALUE
        AS CUSTOMER_LIFETIME_VALUE.AVERAGE_ORDER_VALUE,

    CUSTOMER_LIFETIME_VALUE.PREDICTED_LTV
        AS CUSTOMER_LIFETIME_VALUE.PREDICTED_LTV,

    CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT
        AS CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT,

    CUSTOMER_LIFETIME_VALUE.RENEWAL_LIKELIHOOD_PERCENT
        AS CUSTOMER_LIFETIME_VALUE.RENEWAL_LIKELIHOOD_PERCENT,

    -- SALES PERFORMANCE
    SALES_PERFORMANCE.QUOTA AS SALES_PERFORMANCE.QUOTA,

    SALES_PERFORMANCE.ACTUAL_REVENUE
        AS SALES_PERFORMANCE.ACTUAL_REVENUE,

    SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT
        AS SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT,

    SALES_PERFORMANCE.DEALS_WON
        AS SALES_PERFORMANCE.DEALS_WON,

    SALES_PERFORMANCE.DEALS_LOST
        AS SALES_PERFORMANCE.DEALS_LOST,

    SALES_PERFORMANCE.PIPELINE_VALUE
        AS SALES_PERFORMANCE.PIPELINE_VALUE,

    SALES_PERFORMANCE.AVERAGE_DEAL_SIZE
        AS SALES_PERFORMANCE.AVERAGE_DEAL_SIZE,

    SALES_PERFORMANCE.SALES_CYCLE_DAYS
        AS SALES_PERFORMANCE.SALES_CYCLE_DAYS,

    SALES_PERFORMANCE.CUSTOMER_ACQUISITION_COST
        AS SALES_PERFORMANCE.CUSTOMER_ACQUISITION_COST,

    SALES_PERFORMANCE.GROSS_MARGIN_PERCENT
        AS SALES_PERFORMANCE.GROSS_MARGIN_PERCENT,

    -- PRODUCT DEMAND
    PRODUCT_DEMAND_FREQUENCY.TOTAL_UNITS_SOLD
        AS PRODUCT_DEMAND_FREQUENCY.TOTAL_UNITS_SOLD,

    PRODUCT_DEMAND_FREQUENCY.TOTAL_REVENUE
        AS PRODUCT_DEMAND_FREQUENCY.TOTAL_REVENUE,

    PRODUCT_DEMAND_FREQUENCY.AVG_DAYS_BETWEEN_PURCHASES
        AS PRODUCT_DEMAND_FREQUENCY.AVG_DAYS_BETWEEN_PURCHASES,

    PRODUCT_DEMAND_FREQUENCY.TIMES_PURCHASED_LAST_12_MONTHS
        AS PRODUCT_DEMAND_FREQUENCY.TIMES_PURCHASED_LAST_12_MONTHS,

    PRODUCT_DEMAND_FREQUENCY.TIMES_PURCHASED_LAST_QUARTER
        AS PRODUCT_DEMAND_FREQUENCY.TIMES_PURCHASED_LAST_QUARTER,

    PRODUCT_DEMAND_FREQUENCY.GROWTH_TREND_PERCENT
        AS PRODUCT_DEMAND_FREQUENCY.GROWTH_TREND_PERCENT,

    PRODUCT_DEMAND_FREQUENCY.INVENTORY_RECOMMENDATION
        AS PRODUCT_DEMAND_FREQUENCY.INVENTORY_RECOMMENDATION,

    PRODUCT_DEMAND_FREQUENCY.REORDER_POINT
        AS PRODUCT_DEMAND_FREQUENCY.REORDER_POINT,

    PRODUCT_DEMAND_FREQUENCY.SAFETY_STOCK
        AS PRODUCT_DEMAND_FREQUENCY.SAFETY_STOCK,

    -- MONTHLY SALES TRENDS
    MONTHLY_SALES_TRENDS.UNITS_SOLD
        AS MONTHLY_SALES_TRENDS.UNITS_SOLD,

    MONTHLY_SALES_TRENDS.REVENUE
        AS MONTHLY_SALES_TRENDS.REVENUE,

    MONTHLY_SALES_TRENDS.NUM_ORDERS
        AS MONTHLY_SALES_TRENDS.NUM_ORDERS,

    MONTHLY_SALES_TRENDS.AVG_ORDER_SIZE
        AS MONTHLY_SALES_TRENDS.AVG_ORDER_SIZE,

    MONTHLY_SALES_TRENDS.MONTH_OVER_MONTH_GROWTH_PERCENT
        AS MONTHLY_SALES_TRENDS.MONTH_OVER_MONTH_GROWTH_PERCENT,

    MONTHLY_SALES_TRENDS.YEAR_OVER_YEAR_GROWTH_PERCENT
        AS MONTHLY_SALES_TRENDS.YEAR_OVER_YEAR_GROWTH_PERCENT,

    MONTHLY_SALES_TRENDS.DAYS_TO_SELL_INVENTORY
        AS MONTHLY_SALES_TRENDS.DAYS_TO_SELL_INVENTORY,

    -- DEMAND FORECAST
    DEMAND_FORECAST.FORECASTED_UNITS
        AS DEMAND_FORECAST.FORECASTED_UNITS,

    DEMAND_FORECAST.FORECASTED_REVENUE
        AS DEMAND_FORECAST.FORECASTED_REVENUE,

    DEMAND_FORECAST.CONFIDENCE_LEVEL_PERCENT
        AS DEMAND_FORECAST.CONFIDENCE_LEVEL_PERCENT,

    DEMAND_FORECAST.RECOMMENDED_INVENTORY_LEVEL
        AS DEMAND_FORECAST.RECOMMENDED_INVENTORY_LEVEL,

    DEMAND_FORECAST.LEAD_TIME_DAYS
        AS DEMAND_FORECAST.LEAD_TIME_DAYS
)


-- ============================================================================
-- 4. DIMENSIONS
-- ============================================================================

DIMENSIONS (

    -- CUSTOMERS
    CUSTOMERS.CUSTOMER_ID AS CUSTOMERS.CUSTOMER_ID,
    CUSTOMERS.CUSTOMER_NAME AS CUSTOMERS.CUSTOMER_NAME,
    CUSTOMERS.INDUSTRY AS CUSTOMERS.INDUSTRY,
    CUSTOMERS.COMPANY_SIZE AS CUSTOMERS.COMPANY_SIZE,
    CUSTOMERS.COUNTRY AS CUSTOMERS.COUNTRY,
    CUSTOMERS.STATE AS CUSTOMERS.STATE,
    CUSTOMERS.CITY AS CUSTOMERS.CITY,
    CUSTOMERS.SUBSCRIPTION_TIER AS CUSTOMERS.SUBSCRIPTION_TIER,
    CUSTOMERS.CREATED_DATE AS CUSTOMERS.CREATED_DATE,

    -- PRODUCTS
    PRODUCTS.PRODUCT_ID AS PRODUCTS.PRODUCT_ID,
    PRODUCTS.PRODUCT_NAME AS PRODUCTS.PRODUCT_NAME,
    PRODUCTS.PRODUCT_CATEGORY AS PRODUCTS.PRODUCT_CATEGORY,
    PRODUCTS.PRODUCT_LINE AS PRODUCTS.PRODUCT_LINE,
    PRODUCTS.STATUS AS PRODUCTS.STATUS,
    PRODUCTS.LAUNCH_DATE AS PRODUCTS.LAUNCH_DATE,
    PRODUCTS.END_OF_LIFE_DATE AS PRODUCTS.END_OF_LIFE_DATE,

    -- SALES REPS
    SALES_REPS.REP_ID AS SALES_REPS.REP_ID,
    SALES_REPS.REP_NAME AS SALES_REPS.REP_NAME,
    SALES_REPS.MANAGER_ID AS SALES_REPS.MANAGER_ID,
    SALES_REPS.REGION AS SALES_REPS.REGION,
    SALES_REPS.COMPENSATION_TYPE AS SALES_REPS.COMPENSATION_TYPE,
    SALES_REPS.HIRE_DATE AS SALES_REPS.HIRE_DATE,

    -- REP TERRITORIES
    REP_TERRITORIES.TERRITORY_ID AS REP_TERRITORIES.TERRITORY_ID,
    REP_TERRITORIES.TERRITORY_NAME AS REP_TERRITORIES.TERRITORY_NAME,
    REP_TERRITORIES.COUNTRY AS REP_TERRITORIES.COUNTRY,
    REP_TERRITORIES.STATE AS REP_TERRITORIES.STATE,
    REP_TERRITORIES.REGION AS REP_TERRITORIES.REGION,
    REP_TERRITORIES.ASSIGNED_DATE AS REP_TERRITORIES.ASSIGNED_DATE,
    REP_TERRITORIES.RELEASE_DATE AS REP_TERRITORIES.RELEASE_DATE,

    -- ORDERS
    ORDERS.ORDER_ID AS ORDERS.ORDER_ID,
    ORDERS.CUSTOMER_ID AS ORDERS.CUSTOMER_ID,
    ORDERS.REP_ID AS ORDERS.REP_ID,
    ORDERS.ORDER_DATE AS ORDERS.ORDER_DATE,
    ORDERS.ORDER_MONTH AS ORDERS.ORDER_MONTH,
    ORDERS.EXPECTED_CLOSE_DATE AS ORDERS.EXPECTED_CLOSE_DATE,
    ORDERS.ACTUAL_CLOSE_DATE AS ORDERS.ACTUAL_CLOSE_DATE,
    ORDERS.ORDER_STATUS AS ORDERS.ORDER_STATUS,
    ORDERS.CHANNEL AS ORDERS.CHANNEL,
    ORDERS.DEAL_TYPE AS ORDERS.DEAL_TYPE,

    -- ORDER ITEMS
    ORDER_ITEMS.LINE_ITEM_ID AS ORDER_ITEMS.LINE_ITEM_ID,
    ORDER_ITEMS.ORDER_ID AS ORDER_ITEMS.ORDER_ID,
    ORDER_ITEMS.PRODUCT_ID AS ORDER_ITEMS.PRODUCT_ID,

    -- CUSTOMER SEGMENTS
    CUSTOMER_SEGMENTS.SEGMENT_NAME AS CUSTOMER_SEGMENTS.SEGMENT_NAME,
    CUSTOMER_SEGMENTS.PURCHASE_FREQUENCY
        AS CUSTOMER_SEGMENTS.PURCHASE_FREQUENCY,
    CUSTOMER_SEGMENTS.ENGAGEMENT_LEVEL
        AS CUSTOMER_SEGMENTS.ENGAGEMENT_LEVEL,

    -- INVENTORY
    PRODUCT_INVENTORY.INVENTORY_ID AS PRODUCT_INVENTORY.INVENTORY_ID,
    PRODUCT_INVENTORY.PRODUCT_ID AS PRODUCT_INVENTORY.PRODUCT_ID,
    PRODUCT_INVENTORY.WAREHOUSE_LOCATION
        AS PRODUCT_INVENTORY.WAREHOUSE_LOCATION,
    PRODUCT_INVENTORY.LAST_RESTOCK_DATE
        AS PRODUCT_INVENTORY.LAST_RESTOCK_DATE,
    PRODUCT_INVENTORY.NEXT_RESTOCK_DATE
        AS PRODUCT_INVENTORY.NEXT_RESTOCK_DATE,

    -- CUSTOMER LIFETIME VALUE
    CUSTOMER_LIFETIME_VALUE.FIRST_ORDER_DATE
        AS CUSTOMER_LIFETIME_VALUE.FIRST_ORDER_DATE,

    CUSTOMER_LIFETIME_VALUE.LAST_ORDER_DATE
        AS CUSTOMER_LIFETIME_VALUE.LAST_ORDER_DATE,

    -- SALES PERFORMANCE
    SALES_PERFORMANCE.PERFORMANCE_ID
        AS SALES_PERFORMANCE.PERFORMANCE_ID,

    SALES_PERFORMANCE.REP_ID
        AS SALES_PERFORMANCE.REP_ID,

    SALES_PERFORMANCE.PERFORMANCE_MONTH
        AS SALES_PERFORMANCE.PERFORMANCE_MONTH,

    -- PRODUCT DEMAND FREQUENCY
    PRODUCT_DEMAND_FREQUENCY.FREQUENCY_ID
        AS PRODUCT_DEMAND_FREQUENCY.FREQUENCY_ID,

    PRODUCT_DEMAND_FREQUENCY.PRODUCT_ID
        AS PRODUCT_DEMAND_FREQUENCY.PRODUCT_ID,

    PRODUCT_DEMAND_FREQUENCY.PRODUCT_NAME
        AS PRODUCT_DEMAND_FREQUENCY.PRODUCT_NAME,

    PRODUCT_DEMAND_FREQUENCY.PURCHASE_FREQUENCY
        AS PRODUCT_DEMAND_FREQUENCY.PURCHASE_FREQUENCY,

    PRODUCT_DEMAND_FREQUENCY.PEAK_SEASON
        AS PRODUCT_DEMAND_FREQUENCY.PEAK_SEASON,

    -- MONTHLY SALES TRENDS
    MONTHLY_SALES_TRENDS.TREND_ID
        AS MONTHLY_SALES_TRENDS.TREND_ID,

    MONTHLY_SALES_TRENDS.PRODUCT_ID
        AS MONTHLY_SALES_TRENDS.PRODUCT_ID,

    MONTHLY_SALES_TRENDS.PRODUCT_NAME
        AS MONTHLY_SALES_TRENDS.PRODUCT_NAME,

    MONTHLY_SALES_TRENDS.SALES_MONTH
        AS MONTHLY_SALES_TRENDS.SALES_MONTH,

    -- DEMAND FORECAST
    DEMAND_FORECAST.FORECAST_ID
        AS DEMAND_FORECAST.FORECAST_ID,

    DEMAND_FORECAST.PRODUCT_ID
        AS DEMAND_FORECAST.PRODUCT_ID,

    DEMAND_FORECAST.PRODUCT_NAME
        AS DEMAND_FORECAST.PRODUCT_NAME,

    DEMAND_FORECAST.FORECAST_MONTH
        AS DEMAND_FORECAST.FORECAST_MONTH,

    DEMAND_FORECAST.RISK_LEVEL
        AS DEMAND_FORECAST.RISK_LEVEL,

    DEMAND_FORECAST.MANUFACTURING_DEADLINE
        AS DEMAND_FORECAST.MANUFACTURING_DEADLINE
)


-- ============================================================================
-- 5. BUSINESS METRICS
-- ============================================================================
--
-- IMPORTANT:
--   Metrics are defined against the appropriate table grain.
--
-- ORDERS:
--   Revenue / order / deal metrics.
--
-- ORDER_ITEMS:
--   Product sales / units metrics.
--
-- SALES_PERFORMANCE:
--   Rep performance metrics.
--
-- CUSTOMER_LIFETIME_VALUE:
--   Customer value metrics.
--
-- PRODUCT_INVENTORY:
--   Inventory metrics.
--
-- PRODUCT_DEMAND_FREQUENCY:
--   Demand metrics.
--
-- MONTHLY_SALES_TRENDS:
--   Trend metrics.
--
-- DEMAND_FORECAST:
--   Forecast metrics.
-- ============================================================================

METRICS (

    -- ========================================================================
    -- ORDER / REVENUE METRICS
    -- ========================================================================

    ORDERS.TOTAL_REVENUE
        AS SUM(ORDERS.FINAL_VALUE),

    ORDERS.TOTAL_DEAL_VALUE
        AS SUM(ORDERS.DEAL_VALUE),

    ORDERS.TOTAL_ORDERS
        AS COUNT(ORDERS.ORDER_ID),

    ORDERS.AVERAGE_ORDER_VALUE
        AS AVG(ORDERS.FINAL_VALUE),

    ORDERS.AVERAGE_DEAL_VALUE
        AS AVG(ORDERS.DEAL_VALUE),

    ORDERS.TOTAL_DISCOUNT_PERCENT
        AS SUM(ORDERS.DISCOUNT_PERCENT),

    ORDERS.AVERAGE_DISCOUNT_PERCENT
        AS AVG(ORDERS.DISCOUNT_PERCENT),

    ORDERS.MIN_ORDER_VALUE
        AS MIN(ORDERS.FINAL_VALUE),

    ORDERS.MAX_ORDER_VALUE
        AS MAX(ORDERS.FINAL_VALUE),

    ORDERS.CLOSED_ORDERS
        AS COUNT_IF(ORDERS.ORDER_STATUS = 'Closed'),

    ORDERS.WON_ORDERS
        AS COUNT_IF(
            UPPER(ORDERS.ORDER_STATUS) IN ('WON', 'CLOSED', 'COMPLETED')
        ),

    ORDERS.OPEN_ORDERS
        AS COUNT_IF(
            UPPER(ORDERS.ORDER_STATUS) IN
                ('OPEN', 'PENDING', 'IN PROGRESS', 'NEGOTIATION')
        ),


    -- ========================================================================
    -- ORDER ITEM / PRODUCT SALES METRICS
    -- ========================================================================

    ORDER_ITEMS.TOTAL_UNITS_SOLD
        AS SUM(ORDER_ITEMS.QUANTITY),

    ORDER_ITEMS.PRODUCT_REVENUE
        AS SUM(ORDER_ITEMS.LINE_TOTAL),

    ORDER_ITEMS.TOTAL_LINE_ITEMS
        AS COUNT(ORDER_ITEMS.LINE_ITEM_ID),

    ORDER_ITEMS.AVERAGE_LINE_VALUE
        AS AVG(ORDER_ITEMS.LINE_TOTAL),

    ORDER_ITEMS.AVERAGE_UNIT_PRICE
        AS AVG(ORDER_ITEMS.UNIT_PRICE),

    ORDER_ITEMS.TOTAL_ITEM_DISCOUNT
        AS SUM(ORDER_ITEMS.DISCOUNT_APPLIED),


    -- ========================================================================
    -- PRODUCT METRICS
    -- ========================================================================

    PRODUCTS.PRODUCT_COUNT
        AS COUNT(PRODUCTS.PRODUCT_ID),

    PRODUCTS.AVERAGE_UNIT_PRICE
        AS AVG(PRODUCTS.UNIT_PRICE),

    PRODUCTS.AVERAGE_LIST_PRICE
        AS AVG(PRODUCTS.LIST_PRICE),

    PRODUCTS.AVERAGE_COST_PRICE
        AS AVG(PRODUCTS.COST_PRICE),


    -- ========================================================================
    -- SALES REP METRICS
    -- ========================================================================

    SALES_REPS.REP_COUNT
        AS COUNT(SALES_REPS.REP_ID),

    SALES_REPS.TOTAL_REP_QUOTA
        AS SUM(SALES_REPS.QUOTA),

    SALES_REPS.AVERAGE_REP_QUOTA
        AS AVG(SALES_REPS.QUOTA),

    SALES_REPS.AVERAGE_BASE_SALARY
        AS AVG(SALES_REPS.BASE_SALARY),

    SALES_REPS.AVERAGE_COMMISSION_PERCENT
        AS AVG(SALES_REPS.COMMISSION_PERCENT),


    -- ========================================================================
    -- CUSTOMER SEGMENT METRICS
    -- ========================================================================

    CUSTOMER_SEGMENTS.CUSTOMER_COUNT
        AS COUNT(CUSTOMER_SEGMENTS.CUSTOMER_ID),

    CUSTOMER_SEGMENTS.AVERAGE_SEGMENT_SCORE
        AS AVG(CUSTOMER_SEGMENTS.SEGMENT_SCORE),

    CUSTOMER_SEGMENTS.AVERAGE_RISK_SCORE
        AS AVG(CUSTOMER_SEGMENTS.RISK_SCORE),

    CUSTOMER_SEGMENTS.AVERAGE_SEGMENT_DEAL_SIZE
        AS AVG(CUSTOMER_SEGMENTS.AVERAGE_DEAL_SIZE),

    CUSTOMER_SEGMENTS.AVERAGE_PAYMENT_TERMS
        AS AVG(CUSTOMER_SEGMENTS.PAYMENT_TERMS),


    -- ========================================================================
    -- CUSTOMER LIFETIME VALUE METRICS
    -- ========================================================================

    CUSTOMER_LIFETIME_VALUE.CUSTOMER_COUNT
        AS COUNT(CUSTOMER_LIFETIME_VALUE.CUSTOMER_ID),

    CUSTOMER_LIFETIME_VALUE.TOTAL_CUSTOMER_REVENUE
        AS SUM(CUSTOMER_LIFETIME_VALUE.TOTAL_REVENUE),

    CUSTOMER_LIFETIME_VALUE.TOTAL_CUSTOMER_ORDERS
        AS SUM(CUSTOMER_LIFETIME_VALUE.TOTAL_ORDERS),

    CUSTOMER_LIFETIME_VALUE.AVERAGE_CUSTOMER_ORDER_VALUE
        AS AVG(CUSTOMER_LIFETIME_VALUE.AVERAGE_ORDER_VALUE),

    CUSTOMER_LIFETIME_VALUE.AVERAGE_PREDICTED_LTV
        AS AVG(CUSTOMER_LIFETIME_VALUE.PREDICTED_LTV),

    CUSTOMER_LIFETIME_VALUE.TOTAL_PREDICTED_LTV
        AS SUM(CUSTOMER_LIFETIME_VALUE.PREDICTED_LTV),

    CUSTOMER_LIFETIME_VALUE.AVERAGE_CHURN_RISK
        AS AVG(CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT),

    CUSTOMER_LIFETIME_VALUE.AVERAGE_RENEWAL_LIKELIHOOD
        AS AVG(CUSTOMER_LIFETIME_VALUE.RENEWAL_LIKELIHOOD_PERCENT),

    CUSTOMER_LIFETIME_VALUE.HIGH_CHURN_CUSTOMERS
        AS COUNT_IF(
            CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT > 25
        ),

    CUSTOMER_LIFETIME_VALUE.MEDIUM_CHURN_CUSTOMERS
        AS COUNT_IF(
            CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT >= 15
            AND CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT <= 25
        ),

    CUSTOMER_LIFETIME_VALUE.LOW_CHURN_CUSTOMERS
        AS COUNT_IF(
            CUSTOMER_LIFETIME_VALUE.CHURN_RISK_PERCENT < 15
        ),


    -- ========================================================================
    -- INVENTORY METRICS
    -- ========================================================================

    PRODUCT_INVENTORY.TOTAL_ON_HAND
        AS SUM(PRODUCT_INVENTORY.QUANTITY_ON_HAND),

    PRODUCT_INVENTORY.TOTAL_RESERVED
        AS SUM(PRODUCT_INVENTORY.QUANTITY_RESERVED),

    PRODUCT_INVENTORY.TOTAL_AVAILABLE
        AS SUM(PRODUCT_INVENTORY.QUANTITY_AVAILABLE),

    PRODUCT_INVENTORY.TOTAL_REORDER_LEVEL
        AS SUM(PRODUCT_INVENTORY.REORDER_LEVEL),

    PRODUCT_INVENTORY.AVERAGE_AVAILABLE
        AS AVG(PRODUCT_INVENTORY.QUANTITY_AVAILABLE),

    PRODUCT_INVENTORY.CRITICAL_INVENTORY_PRODUCTS
        AS COUNT_IF(
            PRODUCT_INVENTORY.QUANTITY_AVAILABLE
            < PRODUCT_INVENTORY.REORDER_LEVEL
        ),

    PRODUCT_INVENTORY.WARNING_INVENTORY_PRODUCTS
        AS COUNT_IF(
            PRODUCT_INVENTORY.QUANTITY_AVAILABLE
            >= PRODUCT_INVENTORY.REORDER_LEVEL
            AND PRODUCT_INVENTORY.QUANTITY_AVAILABLE
            < PRODUCT_INVENTORY.REORDER_LEVEL * 1.5
        ),

    PRODUCT_INVENTORY.OK_INVENTORY_PRODUCTS
        AS COUNT_IF(
            PRODUCT_INVENTORY.QUANTITY_AVAILABLE
            >= PRODUCT_INVENTORY.REORDER_LEVEL * 1.5
        ),


    -- ========================================================================
    -- SALES PERFORMANCE / QUOTA METRICS
    -- ========================================================================

    SALES_PERFORMANCE.TOTAL_ACTUAL_REVENUE
        AS SUM(SALES_PERFORMANCE.ACTUAL_REVENUE),

    SALES_PERFORMANCE.TOTAL_PERFORMANCE_QUOTA
        AS SUM(SALES_PERFORMANCE.QUOTA),

    SALES_PERFORMANCE.AVERAGE_QUOTA_ATTAINMENT
        AS AVG(SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT),

    SALES_PERFORMANCE.TOTAL_DEALS_WON
        AS SUM(SALES_PERFORMANCE.DEALS_WON),

    SALES_PERFORMANCE.TOTAL_DEALS_LOST
        AS SUM(SALES_PERFORMANCE.DEALS_LOST),

    SALES_PERFORMANCE.TOTAL_PIPELINE_VALUE
        AS SUM(SALES_PERFORMANCE.PIPELINE_VALUE),

    SALES_PERFORMANCE.AVERAGE_DEAL_SIZE
        AS AVG(SALES_PERFORMANCE.AVERAGE_DEAL_SIZE),

    SALES_PERFORMANCE.AVERAGE_SALES_CYCLE_DAYS
        AS AVG(SALES_PERFORMANCE.SALES_CYCLE_DAYS),

    SALES_PERFORMANCE.AVERAGE_CUSTOMER_ACQUISITION_COST
        AS AVG(SALES_PERFORMANCE.CUSTOMER_ACQUISITION_COST),

    SALES_PERFORMANCE.AVERAGE_GROSS_MARGIN
        AS AVG(SALES_PERFORMANCE.GROSS_MARGIN_PERCENT),

    SALES_PERFORMANCE.PERFORMANCE_RECORD_COUNT
        AS COUNT(SALES_PERFORMANCE.PERFORMANCE_ID),

    SALES_PERFORMANCE.EXCEEDING_QUOTA_REPS
        AS COUNT_IF(
            SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT > 110
        ),

    SALES_PERFORMANCE.ON_TRACK_REPS
        AS COUNT_IF(
            SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT >= 85
            AND SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT <= 110
        ),

    SALES_PERFORMANCE.UNDERPERFORMING_REPS
        AS COUNT_IF(
            SALES_PERFORMANCE.QUOTA_ATTAINMENT_PERCENT < 85
        ),


    -- ========================================================================
    -- PRODUCT DEMAND METRICS
    -- ========================================================================

    PRODUCT_DEMAND_FREQUENCY.DEMAND_TOTAL_UNITS
        AS SUM(PRODUCT_DEMAND_FREQUENCY.TOTAL_UNITS_SOLD),

    PRODUCT_DEMAND_FREQUENCY.DEMAND_TOTAL_REVENUE
        AS SUM(PRODUCT_DEMAND_FREQUENCY.TOTAL_REVENUE),

    PRODUCT_DEMAND_FREQUENCY.AVERAGE_PURCHASE_FREQUENCY_DAYS
        AS AVG(PRODUCT_DEMAND_FREQUENCY.AVG_DAYS_BETWEEN_PURCHASES),

    PRODUCT_DEMAND_FREQUENCY.TOTAL_PURCHASES_LAST_12_MONTHS
        AS SUM(PRODUCT_DEMAND_FREQUENCY.TIMES_PURCHASED_LAST_12_MONTHS),

    PRODUCT_DEMAND_FREQUENCY.TOTAL_PURCHASES_LAST_QUARTER
        AS SUM(PRODUCT_DEMAND_FREQUENCY.TIMES_PURCHASED_LAST_QUARTER),

    PRODUCT_DEMAND_FREQUENCY.AVERAGE_GROWTH_TREND
        AS AVG(PRODUCT_DEMAND_FREQUENCY.GROWTH_TREND_PERCENT),

    PRODUCT_DEMAND_FREQUENCY.TOTAL_RECOMMENDED_INVENTORY
        AS SUM(PRODUCT_DEMAND_FREQUENCY.INVENTORY_RECOMMENDATION),

    PRODUCT_DEMAND_FREQUENCY.TOTAL_REORDER_POINT
        AS SUM(PRODUCT_DEMAND_FREQUENCY.REORDER_POINT),

    PRODUCT_DEMAND_FREQUENCY.TOTAL_SAFETY_STOCK
        AS SUM(PRODUCT_DEMAND_FREQUENCY.SAFETY_STOCK),

    PRODUCT_DEMAND_FREQUENCY.HIGH_GROWTH_PRODUCTS
        AS COUNT_IF(
            PRODUCT_DEMAND_FREQUENCY.GROWTH_TREND_PERCENT > 15
        ),

    PRODUCT_DEMAND_FREQUENCY.MODERATE_GROWTH_PRODUCTS
        AS COUNT_IF(
            PRODUCT_DEMAND_FREQUENCY.GROWTH_TREND_PERCENT >= 5
            AND PRODUCT_DEMAND_FREQUENCY.GROWTH_TREND_PERCENT <= 15
        ),

    PRODUCT_DEMAND_FREQUENCY.DECLINING_PRODUCTS
        AS COUNT_IF(
            PRODUCT_DEMAND_FREQUENCY.GROWTH_TREND_PERCENT < 5
        ),


    -- ========================================================================
    -- MONTHLY SALES TREND METRICS
    -- ========================================================================

    MONTHLY_SALES_TRENDS.TREND_TOTAL_UNITS
        AS SUM(MONTHLY_SALES_TRENDS.UNITS_SOLD),

    MONTHLY_SALES_TRENDS.TREND_TOTAL_REVENUE
        AS SUM(MONTHLY_SALES_TRENDS.REVENUE),

    MONTHLY_SALES_TRENDS.TREND_TOTAL_ORDERS
        AS SUM(MONTHLY_SALES_TRENDS.NUM_ORDERS),

    MONTHLY_SALES_TRENDS.TREND_AVERAGE_ORDER_SIZE
        AS AVG(MONTHLY_SALES_TRENDS.AVG_ORDER_SIZE),

    MONTHLY_SALES_TRENDS.AVERAGE_MOM_GROWTH
        AS AVG(
            MONTHLY_SALES_TRENDS.MONTH_OVER_MONTH_GROWTH_PERCENT
        ),

    MONTHLY_SALES_TRENDS.AVERAGE_YOY_GROWTH
        AS AVG(
            MONTHLY_SALES_TRENDS.YEAR_OVER_YEAR_GROWTH_PERCENT
        ),

    MONTHLY_SALES_TRENDS.AVERAGE_DAYS_TO_SELL
        AS AVG(MONTHLY_SALES_TRENDS.DAYS_TO_SELL_INVENTORY),


    -- ========================================================================
    -- FORECAST METRICS
    -- ========================================================================

    DEMAND_FORECAST.TOTAL_FORECASTED_UNITS
        AS SUM(DEMAND_FORECAST.FORECASTED_UNITS),

    DEMAND_FORECAST.TOTAL_FORECASTED_REVENUE
        AS SUM(DEMAND_FORECAST.FORECASTED_REVENUE),

    DEMAND_FORECAST.AVERAGE_CONFIDENCE_LEVEL
        AS AVG(DEMAND_FORECAST.CONFIDENCE_LEVEL_PERCENT),

    DEMAND_FORECAST.TOTAL_RECOMMENDED_INVENTORY
        AS SUM(DEMAND_FORECAST.RECOMMENDED_INVENTORY_LEVEL),

    DEMAND_FORECAST.AVERAGE_LEAD_TIME_DAYS
        AS AVG(DEMAND_FORECAST.LEAD_TIME_DAYS),

    DEMAND_FORECAST.FORECAST_COUNT
        AS COUNT(DEMAND_FORECAST.FORECAST_ID),

    DEMAND_FORECAST.HIGH_RISK_FORECASTS
        AS COUNT_IF(
            UPPER(DEMAND_FORECAST.RISK_LEVEL) = 'HIGH'
        ),

    DEMAND_FORECAST.MEDIUM_RISK_FORECASTS
        AS COUNT_IF(
            UPPER(DEMAND_FORECAST.RISK_LEVEL) IN ('MEDIUM', 'MODERATE')
        ),

    DEMAND_FORECAST.LOW_RISK_FORECASTS
        AS COUNT_IF(
            UPPER(DEMAND_FORECAST.RISK_LEVEL) = 'LOW'
        )
)


;


-- ============================================================================
-- END OF SEMANTIC VIEW + ANALYST LOGGING
-- ============================================================================
