-- ============================================================================
-- CREATE AGENT FUNCTIONS
-- ============================================================================

USE DATABASE SALES_DATA;
USE SCHEMA PUBLIC;

-- ============================================================================
-- CREATE HELPER FUNCTIONS
-- ============================================================================

CREATE OR REPLACE FUNCTION GET_TABLE_INFO(table_name_param VARCHAR)
RETURNS TABLE (
    TABLE_NAME VARCHAR,
    COLUMN_NAME VARCHAR,
    COLUMN_TYPE VARCHAR,
    COLUMN_DESCRIPTION VARCHAR
)
LANGUAGE SQL
AS
$$
    SELECT 
        TABLE_NAME,
        COLUMN_NAME,
        COLUMN_TYPE,
        COLUMN_DESCRIPTION
    FROM DATA_DICTIONARY
    WHERE UPPER(TABLE_NAME) = UPPER(table_name_param)
    ORDER BY COLUMN_NAME
$$;

CREATE OR REPLACE FUNCTION GET_TABLE_JOINS(table_name_param VARCHAR)
RETURNS TABLE (
    SOURCE_TABLE VARCHAR,
    TARGET_TABLE VARCHAR,
    JOIN_COLUMN VARCHAR,
    RELATIONSHIP_DESCRIPTION VARCHAR
)
LANGUAGE SQL
AS
$$
    SELECT 
        SOURCE_TABLE,
        TARGET_TABLE,
        CONCAT(SOURCE_COLUMN, ' = ', TARGET_COLUMN),
        RELATIONSHIP_DESCRIPTION
    FROM TABLE_RELATIONSHIPS
    WHERE UPPER(SOURCE_TABLE) = UPPER(table_name_param)
    OR UPPER(TARGET_TABLE) = UPPER(table_name_param)
$$;

CREATE OR REPLACE FUNCTION GET_BUSINESS_RULES(rule_type_param VARCHAR)
RETURNS TABLE (
    RULE_NAME VARCHAR,
    RULE_DESCRIPTION VARCHAR,
    THRESHOLD_VALUE NUMBER
)
LANGUAGE SQL
AS
$$
    SELECT 
        RULE_NAME,
        RULE_DESCRIPTION,
        THRESHOLD_VALUE
    FROM BUSINESS_CONTEXT
    WHERE RULE_TYPE = rule_type_param
$$;

CREATE OR REPLACE FUNCTION GET_ALL_TABLES()
RETURNS TABLE (
    TABLE_NAME VARCHAR,
    TABLE_DESCRIPTION VARCHAR
)
LANGUAGE SQL
AS
$$
    SELECT DISTINCT
        TABLE_NAME,
        TABLE_DESCRIPTION
    FROM DATA_DICTIONARY
    ORDER BY TABLE_NAME
$$;

-- ============================================================================
-- VERIFY FUNCTION CREATION
-- ============================================================================

SELECT FUNCTION_NAME
FROM INFORMATION_SCHEMA.FUNCTIONS
WHERE FUNCTION_SCHEMA = 'PUBLIC'
AND FUNCTION_NAME IN ('GET_TABLE_INFO', 'GET_TABLE_JOINS', 'GET_BUSINESS_RULES', 'GET_ALL_TABLES');